[package]
name = "ori_game"
version = "0.1.0"
entry = "raylib.orl"
ori_version = "0.2.0"
description = "Game engine and raylib bindings for Ori language"
authors = ["Ori Team"]
license = "MIT"
repository = "https://github.com/raillen/ori-game"
native_libs = ["raylib"]
